services:
  silent:
    build:
      dockerfile: silent.dockerfile
    image: silent:latest
    container_name: silent-test
    volumes:
      - ./results:/home/gpuot/results
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3', '4', '5', '6', '7']
              capabilities: [gpu]

  ferret:
    build:
      dockerfile: ferret.dockerfile
    image: ferret:latest
    container_name: ferret-test
    volumes:
      - ./results:/home/gpuot/results
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3', '4', '5', '6', '7']
              capabilities: [gpu]
