version: "3.8"

services:
  silent:
    build:
      dockerfile: silent.dockerfile
    image: silent
    command: --name silent-test --runtime=nvidia --gpus '"device=0,1"' -it \
      -m=500m --kernel-memory=500m --memory-swap=500m \
      -v $(pwd)/results:/home/gpuot/results silent

  ferret:
    build:
      dockerfile: ferret.dockerfile
    image: ferret
    command: --name ferret-test --runtime=nvidia --gpus '"device=0,1"' -it \
      -m=500m --kernel-memory=500m --memory-swap=500m \
      -v $(pwd)/results:/home/gpuot/results ferret
